### PR TITLE
fix the bug that the user can add non-csv files

### PR DESCRIPTION
**Pull request by powerseed**
Now, the app allows the user to add a file that is not of type .csv, such as .mp3 and .jpg, into a folder. However, when the user clicks on the file, the activity just finishes without showing any notification to the user. 
My change fixes this bug by forbidding user to add any files that are not of type csv.
When the user does that, a notification shows up which tells the user an error occurred.

### CODE REVIEW

**Comment by cubei** [comment]
The bug you are talking about only occurs if a third party app is used for choosing the file.
With Pull Request #8 the integrated Android file manager only accepts CSV files, other are not selectable.
So are you sure such a fix is needed?

**Comment by powerseed** [comment]
When I run the app on my phone, the bug does occur...
So...
It is OK, I will try to see if there are other bugs.
Thank you for your reply!

**Comment by cubei** [comment]
Which App are you using to select the file?

**Comment by powerseed** [comment]
I am not using any 3-rd party app to select files, it is just a built-in function in my phone's OS.
As the screenshots show, I am able to add .mp3 files into a folder without the changes I made.
Screenshot_2019-07-08-09-21-00-949_FlashCards
Screenshot_2019-07-08-09-26-02-530_FlashCards

**Comment by cubei** [comment]
What Android Fork and version is this?

**Comment by powerseed** [comment]
微信图片_20190708104600

**Comment by cubei** [comment]
I couldn't find anything for model number "DE106". What phone is this?

**Comment by powerseed** [comment]
It is a Chinese brand. Please see the link below.
https://www.kimovil.com/en/where-to-buy-smartisan-nut-r1

**Comment by cubei** [comment]
OK, So [Smartisan OS](https://en.wikipedia.org/wiki/Smartisan_OS) has implemented its own file manager that ignores the MIME type if used as file chooser intent....

**Comment by powerseed** [comment]
Thank you for acccpting my pull requests!

**Pull request merged**
